version: '3.8'

services:
  web:
    build: .
    #command: gunicorn MelodyGuide2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - .MelyGuide2/main/static/main/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD

volumes:
  postgres_data:
